### ISSUE TITLE
Multiline Text

### ISSUE THREAD

**Issue by PouriaAmid** [datalogics/adobe-pdf-library-samples#27]
Hi,
is there any simple way to create multiline text objects without breaking down the string into chars and create multiple text objects for each line?

Using .net framework and APFL 15.

**Comment by datalogics-pgallot** [comment]
@PouriaAmid you might want to take a look at this [blog article](https://blogs.datalogics.com/2017/02/21/create-toc-from-bookmarks/), particularly the practiceLayout and layoutTOC routines.

**Comment by PouriaAmid** [comment]
Thanks for reply.
The solution is to split the text in lines and add a new TextRun for each line.
`
foreach (var line in lines)
{
	Text.AddRun(new TextRun(line, font, gs, ts, matrix.Translate(x, y)));
	y -= ts.FontSize;
}
`
