### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by PouriaAmid** [datalogics/adobe-pdf-library-samples#30]
Im trying to create PDF/A documents in MVC /C#.
When i run the code on the server still get an error:
` var pdfa = doc.CloneAsPDFADocument(PDFAConvertType.RGB3u, new PDFAConvertParams());`

`System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt. iisexpress.exe`

Save as Standard PDF is working perfectly but the converting doesnt.
The same code works also perfect in a console application.

**Comment by datalogics-josepha** [comment]
Hello,

Have you opened an inquiry with our Support department yet (tech_support@datalogics.com)?

If not, please do so in order to more direct assistance.  A small runnable sample along with the input PDF demonstrating the issue will help us investigate the issue.

Thanks.

**Comment by PouriaAmid** [comment]
Hi,
i finally found the solution.
You get this error only when you debug the application.
On IIS the debugging should be Off and on .Net Core "OutOfProcess" should be used as HostingModel.
