### ISSUE TITLE
Missing Binaries for .NET

### ISSUE THREAD

**Issue by jhosein** [datalogics/adobe-pdf-library-samples#36]
I've downloaded the sample code and want to run DotNETViewer_32Bit.sln.

I have received the following error: 
`The type or namespace name 'DotNETViewerComponent' could not be found (are you missing a using directive or an assembly reference?)
`
I have tried the following: 
1. Looking in the Binaries folder in the DotNET folder
2. Adding the DotNETViewerComponent project file to the DotNETViewer solution
3. Adding the DotNETViewer project as a dependency to the solution.

**Comment by datalogics-mdawson** [comment]
Hello Jonathan

Thank you for reaching out to us, and in taking an interest in our products at Datalogics.

We provide the adobe-pdf-library-samples public github repository to allow customers and prospects to open and read the sample programs we provide with Adobe PDF Library. But they are only intended here for viewing and research.  These samples can't be run without also installing the APDFL host product. 

We provide detailed documentation for the product here:

https://dev.datalogics.com/adobe-pdf-library/

And a great deal of technical background about APDFL on our Knowledge Base:

https://kb.datalogics.com/display/KB/Adobe+PDF+Library

You can also learn about installing a trial version of the product at our product web site:

https://www.datalogics.com/products/pdf/pdflibrary/

Further, if you would like to talk to a Sales representative, feel free to send a message to tech_support@datalogics.com. 

I hope you find this helpful.

Mark Dawson
Technical Writer
Datalogics
