### ISSUE TITLE
Missing image_as_text.jpg sample input file

### ISSUE THREAD

**Issue by naumanna** [datalogics/adobe-pdf-library-samples#40]
I'm trying to follow the OCR samples and they expect this file to exist, but it is not in the repository:

`Sample_Input/text_as_image.jpg`

From the documentation:

```The sample uses a JPG image called “text_as_image.jpg” as the input file, and then processes this image with the Optical Recognition engine. The JPG input file features about 450 words from the text of an ancient speech. After the text is extracted from the image, the program places the image and the text drawn from that image in a PDF output document.```

**Comment by datalogics-mdawson** [comment]
Good morning

The adobe-pdf-library-samples repository is a public repository that we provide to our Adobe PDF Library customers and prospects. The goal is to allow you to look at our sample programs, but you can't run them without installing the APDFL product as well.

We provide only the sample program files for C++ (.cpp), C# (.cs), and Java. The project files and sample input files are not included. 

If you would like to speak to our Sales and Support staff, they can help you install an evaluation version of the APDFL product.

https://www.datalogics.com/products/pdf/pdflibrary/

Mark Dawson
Datalogics, Inc.

**Comment by naumanna** [comment]
I am already a customer, I just didn't realize the sample input file would be in the APDFL and not in this sample repository.  I see the file now in APDFL.  Sorry for the trouble. I'll close this issue.

**Comment by datalogics-mdawson** [comment]
No trouble at all.  I'm happy to help.
