### ISSUE TITLE
undefined references to GLIBC_2.14 on Linux

### ISSUE THREAD

**Issue by linux-is-beste** [datalogics/adobe-pdf-library-samples#53]
we are facing some linking issues with APDFL 18 on CentOS 6.10

Steps to reproduce ...

    cat /etc/redhat-release

        CentOS release 6.10 (Final)

    cd APDFL18.0.3/CPlusPlus/Sample_Source/Text/ExtractText

    OS=i80386linux BUILD_64_BIT=true make

    ../../../Binaries/libDL180pdfl.so: undefined reference to `memcpy@GLIBC_2.14'

there are some additional undefined references like 'something@GLIBCXX_3.4.15' but then can be workd around with a different libstdc++.so

**Comment by datalogics-robb** [comment]
Cent OS 6 is not a supported platform for APDFL 18.  Cent OS 7 is supported.

See: https://dev.datalogics.com/adobe-pdf-library/setting-up-adobe-pdf-library/

**Comment by linux-is-beste** [comment]
Thank you robb - thats good to know. Maybe you should add it more prominent in the Readme.md?

>> from https://dev.datalogics.com/adobe-pdf-library/setting-up-adobe-pdf-library
... Redhat Enterprise Linux  7/CentOS 7, or  GLIBC 2.17 or later ...

In my personal opinion it would be better to support it until the end of its EEOL period, especially considering that RHEL is a commercial product (Extended EOL for RHEL6 ends on 30 June 2024)

**Comment by datalogics-pgallot** [comment]
@linux-is-beste if CentOS 6 support is imperative, have you tried APDFL v15.0.4 ?

**Comment by linux-is-beste** [comment]
> @linux-is-beste if CentOS 6 support is imperative, have you tried APDFL v15.0.4 ?

yes - we have been using APDFL v15.x it for years. But now our product management (callassoftware.com) has decided to switch to APDFL v18, mainly because APDFL v15.x is no longer being developed.

Actually, CentOS6 or RHEL6 is not mandatory for ourselves, but for those of our customers who are not willing (or able) to upgrade to a newer OS version.

**Comment by datalogics-pgallot** [comment]
While Adobe may not be further developing APDFL v15.x, Datalogics expects to be supporting our version of it for the foreseeable future.

**Comment by linux-is-beste** [comment]
Thank you,

but our products are multiplatform (Windows, MacOS, Linux). So if possible we would prefer to use the same APDFL version on all platforms.

Apart from that, the new version seems to bring some welcome improvements compared to its predecessor.

**Comment by datalogics-mdawson** [comment]
We really appreciate your loyalty to Datalogics as our customer.

We regularly issue updates to both Adobe PDF Library 15 and 18 to improve both products and to respond to requests from our users. In particular we have made it a priority to make sure that our products are compatible with the most recent versions of the operating system platforms and open source software tools they support and rely on.

It would be difficult at this point to justify the amount of effort required to make Adobe PDF Library 18 compatible with CentOS 6, especially given that the market has moved to CentOS 7. 

But we are happy to speak with you about the matter further. If you like, feel free to reach out to our Support team at tech_support@datalogics.com.

**Comment by linux-is-beste** [comment]
interesting ... only the 64bit variant has this GLIBC_2.14 version issue.

With the 32bit variant everything is fine. For me it looks like it is compiled against GLIBC_2.11.

In other words: It is not impossible _per se_ to "downgrade" the glibc version binding

**Comment by datalogics-robb** [comment]
It is basically random whether or not a versioned symbol from a later version gets used, so the fact that 32-bit doesn't raise the same error is just luck.  Our 32-bit and 64-bit packages are built on the same machine with the same compiler.
